name: Auto Sync Upstream everyday

on:
  schedule:
    # Daily for now
    - cron: '9 7 * * *'
  workflow_dispatch:

permissions: write-all

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Sync and merge upstream repository with your current repository
        uses: dabreadman/sync-upstream-repo@v1.0.0.b
        with:
          # URL of gitHub public upstream repo
          upstream_repo: "https://github.com/actions/starter-workflows.git"
          # Branch to merge from upstream (defaults to downstream branch)
          upstream_branch: main
          # Branch to merge into downstream
          downstream_branch: master
          # GitHub Bot token
          token: ${{ secrets.GITHUB_TOKEN }}
